# Generated by Django 4.2.6 on 2023-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ss',
            field=models.CharField(choices=[('s', 's'), ('m', 'm'), ('l', 'l')], default='m', max_length=7),
        ),
    ]
