# Generated by Django 4.2.6 on 2023-12-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_image_image_image_image1_image_image10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_size',
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image10',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image5',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image6',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image7',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image8',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image9',
            field=models.ImageField(default='Null', upload_to='static/items_images'),
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
