# Generated by Django 4.2.6 on 2023-12-18 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_remove_item_item_size_item_image1_item_image10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('item_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orderd', to='base.item')),
                ('user_ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phon_number', models.CharField(max_length=11)),
                ('user_near_living', models.CharField(max_length=60)),
                ('user_imge', models.ImageField(default='lol/static/user.png', upload_to='static/user_imag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_prof',
            name='user',
        ),
        migrations.DeleteModel(
            name='user_orders',
        ),
        migrations.DeleteModel(
            name='user_prof',
        ),
    ]
