# Generated by Django 4.2.6 on 2023-12-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_orders_user_pro_remove_user_prof_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amaont',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='size',
            field=models.TextField(default=''),
        ),
    ]
