# Generated by Django 4.2.6 on 2023-12-18 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_orders_user_ord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amaont',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='item_ord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_orderd', to='base.item'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='size',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
