# Generated by Django 4.2.6 on 2023-12-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_orders_amaont_alter_orders_item_ord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_pro',
            name='user_imge',
            field=models.ImageField(blank=True, default='lol/static/user.png', null=True, upload_to='static/user_imag'),
        ),
    ]
