# Generated by Django 4.2.6 on 2023-12-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_pro_user_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_img',
            field=models.ImageField(default='Null', upload_to='static/deal_img'),
        ),
    ]
